name: dev-done Pipeline

on:
  push:
    branches:
      - dev-done
    # paths:
    #   - 'app-code/**'

  workflow_dispatch:

env:
  DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
  PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
  DEV_API_GATEWAY_URL: ${{ vars.DEV_API_GATEWAY_URL }}
  PROD_API_GATEWAY_URL: ${{ vars.PROD_API_GATEWAY_URL }}

jobs:
  trigger_dev_staging_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send to DEV API Gateway
        run: |
          # Create JSON payload directly in this step
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TRIGGER_TYPE="pull_request"
            PR_ID="${{ github.event.pull_request.number }}"
          else
            TRIGGER_TYPE="push"
            PR_ID="null"
          fi
          
          # Create the JSON payload without using jq
          PAYLOAD="{\"source_repository\":\"${{ github.repository }}\",\"destination_branch\":\"${{ github.ref_name }}\",\"commit_hash\":\"${{ github.sha }}\",\"trigger_type\":\"${TRIGGER_TYPE}\",\"pr_id\":${PR_ID}}"
          echo "Payload : $PAYLOAD"

          # Send the request
          echo "Sending to dev endpoint: ${{ env.DEV_API_GATEWAY_URL }}/pr-merged"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ env.DEV_API_KEY }}" \
            -d "${PAYLOAD}" \
            "${{ env.DEV_API_GATEWAY_URL }}/pr-merged"

      - name: Send to PROD API Gateway
        run: |
          # Create JSON payload directly in this step
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TRIGGER_TYPE="pull_request"
            PR_ID="${{ github.event.pull_request.number }}"
          else
            TRIGGER_TYPE="push"
            PR_ID="null"
          fi
          
          # Create the JSON payload without using jq
          PAYLOAD="{\"source_repository\":\"${{ github.repository }}\",\"destination_branch\":\"${{ github.ref_name }}\",\"commit_hash\":\"${{ github.sha }}\",\"trigger_type\":\"${TRIGGER_TYPE}\",\"pr_id\":${PR_ID}}"
          echo "Payload : $PAYLOAD"

          # Send the request
          echo "Sending to prod endpoint: ${{ env.PROD_API_GATEWAY_URL }}/pr-merged"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ env.PROD_API_KEY }}" \
            -d "${PAYLOAD}" \
            "${{ env.PROD_API_GATEWAY_URL }}/pr-merged"

  snyk_scan:
    needs: trigger_dev_staging_api # Ensures API trigger completes first
    uses: ./.github/workflows/snyk-scan.yml # Calls the Snyk scan workflow
    secrets:
      SNYK_AUTH_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
